# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        patterns: ["eslint*", "@types/*", "typescript"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly